### PR TITLE
ported to gtk+3

### PR DESCRIPTION
**Pull request by sanatankc**
I have ported this activity to gtk+3. There are currently no errors in logs. It looks same as before, except SpinButton.
screen shot 2017-12-16 at 9 09 10 pm
I don't know if it is supposed to be like this.

### CODE REVIEW

**Comment by walterbender** [comment]
The spin button text is impossible to read. Can you please work on that?

**Comment by walterbender** [comment]
Also, there are a few tweaks needs: Line 237 of activity.py should be:

return (year % 4 == 0 and not year % 100 == 0) or year % 400 == 0
and there are a few pylint errors.

**Comment by sanatankc** [comment]
@walterbender, I don't know how to how to make styling changes in GTK. I guess, it is by css. But don't know exactly how?

**Comment by walterbender** [comment]
I will try to find you an example of where the spinners are properly styled.
(Seems to be a general problem with spinners in Sugar. We'll have to dig into the CSS)

Something here I suspect:
https://github.com/sugarlabs/sugar-artwork/blob/master/gtk3/theme/gtk-widgets.css.em#L181

**Comment by quozl** [comment]
Good start, well done!  Reviewed.

- [x] the `draw` signal is connected to an `_expose_cb`; please rename the callback to `_draw_cb`,
- [x] the [`Gtk.Widget.signals.draw`](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.draw) signal is supposed to return a `bool`; please decide what to return, and return it explicitly,
- [x] the `Gtk.Widget.signals.draw` signal has differently named second argument, a `cairo.Context` which may not be the whole display area; please use the same argument names as in the documentation, and use `cr` as the context to draw into rather than creating a context.

**Comment by sanatankc** [comment]
Thanks @quozl. I have fixed issues you mentioned.

@walterbender, should I make an pull to sugar-artwork for fix or I should do something locally to fix this.

I think we need to add something like this.
```css
spinbutton entry {
    color: black
}
```

**Comment by quozl** [comment]
Thanks.

- [x] please use `cr` rather than `cairo_context` because it is the name used by documentation, and the majority of activities,

In a sample of 27 activity repositories, the most frequently used names for this argument were;

Name | Frequency
------------ | -------------
`cr` | 12 of 27
`context` | 8 of 27
`ctx` | 5 of 27

And I've a question for you about `calculate_bio`; it is more correct to use [`queue_draw`](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.queue_draw) instead of directly calling the `_draw_biorhytm` (sic) method?  If so, there would be no need to create a cairo context.

**Comment by sanatankc** [comment]
Yeah, you are right. It's better to re-shedule a draw instead of directly calling `_draw_biorhthm`.

**Comment by sanatankc** [comment]
Sorry, I have added some extra files in the commit. Those were for live-reload of activity.

**Pull request merged**
