### PR TITLE
Display three sine waves on graph with X axis for time.

### PR DESCRIPTION
**Pull request by nswarup14**
Implements  #9 

**Files Changed**
1) `activity.py`

**Updates**
Each sine wave represents one of the three attributes of a BioRhythm: Physical, Emotional and Intellectual
The waves represent the varying values for all three attributes for a period of two weeks, covering a week before and after the selected date.

Tested on Ubuntu 18.04 Sugar v0.114

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested f8da381 on an Ubuntu 18.04 virtual machine with 1024x768 display resolution.

Screenshot_ubb_2019-06-18_13:57:15

* [x] the bar graph has been truncated,
* [x] the legend of the bar graph has been truncated,
* [x] the bars have opposite sign to the graph,
* [x] the current day is not shown on the graph,
* [x] the graph lines are not curved; they are a series of segments,
* [x] the graph lines stop before they reach the vertical axes,
* [x] the graph is redrawn when the stop button is pressed, in particular the X axis dates.

Also, matplotlib is not usually installed on systems that run Sugar.  Fix is to run `sudo apt install python-matplotlib`.  If not done, the activity does not start, and this error is in logs;

```log
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 178, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/Biorhythm.activity/activity.py", line 41, in <module>
    from matplotlib.figure import Figure
ImportError: No module named matplotlib.figure
```

* [ ] handle this error more gracefully?

**Comment by nswarup14** [comment]
- [x] the bar graph has been truncated,
 - [x] the legend of the bar graph has been truncated,
I dont seem to have such a problem. Perhaps it has something to do with the screen resolution? I have attached a screenshot for reference.
Screenshot from 2019-06-19 11-13-10

 - [x] the bars have opposite sign to the graph,
Has been fixed
 - [x] the current day is not shown on the graph,
I have choosen to highlight the current day with a purple color and bolder text.
 - [x] the graph lines are not curved; they are a series of segments,
Yes. I am unable to think of an alternative where I can plot the sine graphs continuously rather than join the line segments. 
 - [x] the graph lines stop before they reach the vertical axes,
Yes. Is that a cause for concern? I chose to keep it that way because the x axis doesn't start from zero, rather an arbitrary date, hence a gap is necessary.
 - [x] the graph is redrawn when the stop button is pressed, in particular the X axis date
I have fixed that.

**Comment by quozl** [comment]
Thanks.  Good progress.

#### Truncated display

Still occurs on Ubuntu 18.04 with 1024x768 pixel resolution.  Please test several resolutions.  Wikipedia has a list of common display resolutions.  Most likely cause is that you have specified exact sizes in _initial_plot_ that have no relationship to the display size.  You could instead use a ratio of the display size.

#### Graph lines not curved

You have chosen the number of points to graph; one per day.  That's why there are line segments.  You could instead plot more points each day; between ten and fifty.

#### Unnecessary redraws

This still happens.

* run your activity with GTK_DEBUG set to updates,
```
GTK_DEBUG=updates sugar-activity
```
* while interacting with the activity, watch for red flashes,

References:
* [Running GTK+ Applications](https://developer.gnome.org/gtk3/stable/gtk-running.html)

It may be a latent problem, but adding a graph makes the problem worse.  You could either find out why `_draw_cb` is being called during stop, or pay attention to the Cairo context to see if the area of screen that needs to be redrawn intersects with the graph.

I've experimented for you with this code added to `_draw_cb`:

```python
import sys
clip, rect = Gdk.cairo_get_clip_rectangle(cr)
print >>sys.stderr, "%r" % repr([clip, rect.x, rect.y, rect.width, rect.height])
```

Result on initial drawing and on stop is `[True, 0, 0, 162, 715]` which is the area of the _Gtk.DrawingArea_ that the _Biorhythm_ class inherits.  It looks like you are drawing with Matplotlib outside that area.  I don't see how this is working, but it clearly does.  I think you could make another class for the line graph, rather than overload the bar graph widget.  That will give you a separate draw callback you can rely on.

**Comment by nswarup14** [comment]
@quozl 
I agree with your observation that the `Biorthym` widget is being overloaded. I made a new class `Plot` to embed the line graph and keep both on them in a `Gtk.Container`, which is set the main canvas for the activity.

It works, but there are weird observations
1) I removed the `self.draw()` method which seemed to cause the `draw` signals in a race condition, as `self.queue_draw()` itself emits `draw signal`.

2) However, on activity start the `draw` signal for the line graph is being called twice as verified by calling `print` statements in `_draw_cb()` signal handler. Even on clicking the buttons to change date on the toolbar, the method is being called twice. I believe every time the window is optimised, the signals are being emitted. However on changing the dates, the method is executed only once.

3) Also on changing the `Today` date for the very first time, the graph is not changing its values (visually). However I verified that the `_draw_cb()` method is being executed, which means that the `draw` signal is being emitted correctly. However, in the `def calculate_graph_values()` method, while the values of `p, e, i, labels` are being updated the plot is not being redrawn.

I would kindly need guidance on these issues, as I was not able to solve them despite a lot of googling and documentation.

Thanks!

**Comment by quozl** [comment]
Re: 1, that's not a race condition, that's signal recursion or
repeated drawing.  In general, the callback for the Gtk.Widget::draw
signal should never call Gtk.Widget.queue_draw. or Gtk.Widget.draw.
It was correct of you to remove the self.figure.canvas.draw().

Re: 2, yes, multiple draw signals are common during start, usually
caused by resizing of the Gtk.Window to fit the available display
area.  Any toolbar interaction that covers and then exposes the
rectangle owned by self._plot will cause another draw signal.
Changing the dates causes notify::value signal which calls a function
which eventually calls Gtk.Widget.queue_draw.

Re: 3, you'll have to fix this.  Keep working on it; look at the
source code for the FigureCanvas widget, as documentation is not
always up to date.  Try making small reproducer built from the GTK
Hello World, consisting of a Gtk.Window containing a FigureCanvas, and
test the draw signal there.

**Comment by nswarup14** [comment]
@quozl 
Thank you for the suggestions.
I shall try to write a reproducer and continue the work from there.

**Comment by nswarup14** [comment]
Here is the reproducer I wrote
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

from matplotlib.backends.backend_gtk3agg import (
    FigureCanvasGTK3Agg as FigureCanvas)
from matplotlib.figure import Figure
import numpy as np


class Window(Gtk.Window):
    def __init__(self):
        super().__init__()

        self.set_default_size(1200, 800)
        self.set_title("Reproducer")
        
        self.connect("delete-event", Gtk.main_quit)

        self.figure = Figure(figsize=(5, 4), dpi=100)
        self._plot = FigureCanvas(self.figure)
        self._plot.set_size_request(800, 600)
        self.axes = self.figure.add_subplot(111)

        self.click = False


        button = Gtk.Button.new_with_label("Click Me")
        button.connect("clicked", self.on_click_me_clicked)
        
        container = Gtk.Box()
        container.pack_start(self._plot, True, True, 0)
        container.pack_start(button, False, True, 0)
        self.add(container)

        self.connect("draw", self._draw_cb)

    def _draw_cb(self, widget, cr):
        print('draw')
        self.axes.clear()
        t = np.arange(0.0, 3.0, 0.01)
        if self.click:
            s = np.sin(2*np.pi*t)
        else:
            s = np.cos(2*np.pi*t)
        self.axes.plot(t, s)

    def on_click_me_clicked(self, btn):
        self.queue_draw()
        if self.click:
            self.click = False
        else:
            self.click = True


if __name__ == "__main__":
    
    win = Window()
    sw = Gtk.ScrolledWindow()
    win.add(sw)
    # A scrolled window border goes outside the scrollbars and viewport 
    sw.set_border_width(10)

    sw.add_with_viewport(win._plot)

    win.show_all()
    Gtk.main()
```
In the reproducer, on clicking the button _Click me_, the plot is being redrawn on the first click itself. `self.queue_draw()` ensures this happens.

However, in the activity, upon changing the `Today` date, the plot is not being redrawn on the first click, but only on clicking twice. It is puzzling because the `draw` signal is emitted and the its corresponding handler is executed as well. However, the line graph is not updated.

Despite the reproducer mimicking the same operation as the activity, the behavior is different. Kindly advise.

Thanks!

**Comment by quozl** [comment]
Thanks for the reproducer.  I tried it out.  I found a few things to
fix;

- Window can only have one child, so the Gtk.ScrolledWindow is moved
  into Window, with the Gtk.Box inside it, and the button and
  FigureCanvas inside it,

- the ::draw signal was connected to the Window yet it was coded to
  redraw the FigureCanvas, so the connect is moved there,

- the ::draw signal handler was calling Gtk.Widget.queue_draw for the
  Gtk.Window, rather than for the FigureCanvas,

- to use Python 2, the call to super().__init__() was changed to
  Gtk.Window.__init__(self),

It showed an interesting new symptom; if a smaller window from another
application is dragged to obscure part of the FigureCanvas, the curve
is redrawn out of phase.  That could be the same underlying problem
that led to "3" in comments above six days ago.

My changed reproducer;

http://dev.laptop.org/~quozl/y/1hgdPf.txt

**Comment by quozl** [comment]
The FigureCanvas has it's own draw signal handler, and behaves as if
it is double buffered.  So there's no need for a draw signal handler
for the FigureCanvas widget.

http://dev.laptop.org/~quozl/y/1hgebN.txt is fixed reproducer.

The init and click handler calls the replot, and the replot calls
queue_draw.

The click handler must call replot _after_ changing the boolean,
otherwise the first click is ineffective.

**Comment by nswarup14** [comment]
@quozl 
Thank you for testing the reproducer. Based on your modifications, I was able to understand the issue of redraws, why the line graph was not re-plotting on the first click and the behavior of FigureCanvas.

Now the issue of not replotting on the first click is resolved. It seemed as if the updated points on the graph were being replotted with a delay of one click. By calling `queue_draw()`, after calculating the newer plot points, the issue is resolved.

Modified checklist
- [x] the bar graph has been truncated,
- [x] the legend of the bar graph has been truncated,
Should the space division between the two types of graphs be kept at 50% each? Perhaps the line graph can be given more space? Kindly advise
- [x] the bars have opposite sign to the graph,
- [x] the current day is not shown on the graph,
- [x] the graph lines are not curved; they are a series of segments,
- [x] the graph lines stop before they reach the vertical axes,
- [x] the graph is redrawn when the stop button is pressed, in particular the X axis dates.
Yes, even now, when the stop button is pressed, the `_draw_cb` handler for the bar graph widget is being run. However, the line graph is not being redrawn. Should I refactor the code so that the former does not take place?

Thanks!

**Comment by rhl-bthr** [comment]
Thanks

**Comment by quozl** [comment]
Tested 0dff54e on Ubuntu 19.04

* [x] there was no sine wave graph shown.

I had to go back to 2ef013e before a sine wave graph appeared.

**Comment by nswarup14** [comment]
@quozl 
I was surprised when I too ran into the same issue right now, nut it turns out that I had not installed `matplotlib`, `scipy` and `numpy`. After installing the above, the line graph appeared on https://github.com/sugarlabs/biorhythm/commit/0dff54e2d274666258f8ba5ebce1a7f46fa7b6e5

After https://github.com/sugarlabs/biorhythm/commit/2ef013e83dfdfd576e1708ac89aaac041ea8e938, I have used `numpy` and `scipy` as well, so perhaps thats the reason.

Thanks

**Comment by quozl** [comment]
Okay, but the log doesn't show that, and there's no indication of missing dependencies.  I'll check what is installed.

**Comment by quozl** [comment]
Thanks.  Installing `python-scipy` fixed it.

* [x] please list the missing dependencies in the log; my earlier request was to handle this error more gracefully, but what you've done is to eliminate it entirely, which led to not seeing the curves,
* [x] axis titles are truncated, see screenshot below;

Screenshot_udd-clone_2019-07-08_16:56:36

Note the black pixels just below the current date.

Reviewed as-at 0dff54e;
* [x] variable `import_plot` has a name that does not explain what it is for; choose a better name, bearing in mind that it is boolean,
* [x] variable `_plot` and class `Plot` are ambiguous; a new developer would think there are two plots on display; choose a better name,
* [x] function `calc` in two classes has similar code to convert data and handle ValueError; refactor,
* [x] new flake8 output is seen; please avoid adding.

**Comment by nswarup14** [comment]
@quozl 
Updated checklist
> - [x]  please list the missing dependencies in the log; my earlier request was to handle this error more gracefully, but what you've done is to eliminate it entirely, which led to not seeing the curves,

I have added it in the latest commit.
> - [x] axis are truncated. Black pixels just below the date

I am not getting the truncated display for the axis names. There are no black pixels as well, at the bottom. I have attached a screenshot for reference.
Screenshot (18)
> - [x] variable import_plot has a name that does not explain what it is for; choose a better name, bearing in mind that it is boolean,

I have updated the variable name to `import_plot_error`.
> - [x] variable _plot and class Plot are ambiguous; a new developer would think there are two plots on display; choose a better name,

I have changed the name of the class to `LineGraph` to prevent the confusion.
> - [x] new flake8 output is seen; please avoid adding.

I have removed as many as possible
> - [x] function calc in two classes has similar code to convert data and handle ValueError; refactor,

I have refactored that and made it into a single function.

Thanks

**Comment by quozl** [comment]
Thanks.  Reviewed b0bb65f.

* [x] the new error message has extra whitespace; please fix; here's what it looks like in log;
```log
1562732722.234531 ERROR root: Please install the libraries python-scipy,     python-numpy and python-matplotlib through apt or     your favourite package manager, to display the line graph
```

* [x] new variable `import_plot_error` does not explain what it is for; please choose a better name?  Imagine yourself as a new developer reading one of the _references_ to the new variable, such as line 93, can you figure out what it is for without having to read where it is defined?

* [x] flake8 messages occur in areas where you have changed the code;

```log
./activity.py:449:13: E128 continuation line under-indented for visual indent
./activity.py:470:80: E501 line too long (83 > 79 characters)
./activity.py:471:80: E501 line too long (83 > 79 characters)
./activity.py:472:80: E501 line too long (83 > 79 characters)
./activity.py:495:80: E501 line too long (81 > 79 characters)
./activity.py:502:28: E128 continuation line under-indented for visual indent
./activity.py:503:28: E128 continuation line under-indented for visual indent
./activity.py:505:28: E128 continuation line under-indented for visual indent
./activity.py:506:28: E128 continuation line under-indented for visual indent
./activity.py:508:28: E128 continuation line under-indented for visual indent
./activity.py:509:28: E128 continuation line under-indented for visual indent
```

* [x] the truncation of the axis titles continues to occur; this is on Ubuntu 18.04 with display dimensions of 1024x768; please reproduce those dimensions and test?  I've looked at your changes so far, and it seems unlikely to be something you've done, but rather a latent flaw in the source code before you worked on it, so what you did was expose the flaw.  Although I'm not entirely sure why you declare figsize=(100,100) nor why you add both children of the Gtk.Box with same flags.

**Comment by nswarup14** [comment]
@quozl 
I have fixed the extra white spaces in the error log message and flake8 errors.
I have changed the variable name to `successful_import`.

As for the truncation issue, I tried to reproduce the same resolution by changing in my Windows settings (I use a Ubuntu 18.04 VM with Native Sugar v0.114). I did not see any truncation and the axis titles were displayed correctly. 

I have updated the display ratio of the two graphs to 1:3 (Bar Graph : Line graph). This increases the size of the dates in the line graph as well as the legend, thus enabling the user to see the graph more clearly.

**Comment by quozl** [comment]
Thanks!  Good progress.

I don't think `successful_import` tells anything useful to a developer reading the _references_ to it.  I'll merge it with a name of `use_line_graph`.

You're not getting anywhere with the truncated figure canvas problem, and you've not made any suggestions as to how to diagnose it further, so I'll take control of that ...

I've spent some time trying to understand the code.  It wasn't easy, as there is much that is not needed, and the usual principles of modularity were broken.

But I did find out that the Figure is larger than the FigureCanvas, and that causes the X axis label to depart from visibility.  Fix is to call _set_constrained_layout_.

Then it was a matter of turning off the Gtk.Box expand property of the bar graph child, calling _set_size_request_ for the bar graph to set a minimum width, while **not** calling _set_size_request_ for the line graph, and this allows the line graph to grow to the space available.

Please review and test my hacked source code as at de925c4e43b864be37e331862bcc86d0c372dc26.  The diff is not very readable, as I changed a lot of things without lots of little commits.

Hope that helps!

**Comment by nswarup14** [comment]
@quozl 
Thanks.

Reviewed https://github.com/sugarlabs/biorhythm/commit/de925c4e43b864be37e331862bcc86d0c372dc26. Yes, the code is a lot more modularized and unnecessary functions are removed or refactored.

`set_constrained_layout` is only added to matplotlib3.1 and above. For 19.04 and below, on installing `python3-matplotlib` through apt, only version 2.1.1 is installed. I therefore installed matplotlib via `pip install --user matplotlib=3.1.1` again. Should I include in the import log message about the version number?

Regarding the parameters to `box.pack_start()`, I tried to set it to `False, False` for the Bar graph widget earlier, but that just made the entire bar graph disappear. I do not understand why it works now.

Tested the patch on Ubuntu 18.04 and Sugar v0.114, with matplotlib updated to 3.1.1 and the line graph did not change on changing the dates. I will try to find out the reason why.

Regarding the FIXME included, the `self._scale` is set to 250 from an earlier work that was already in `master`. Please [see](https://github.com/sugarlabs/biorhythm/blob/master/activity.py#L300). I do not know why it was set to 250 but my guess is that, it was done to scale the trigonometric values so that the graph can be displayed with a higher value. 

Thanks.

**Comment by quozl** [comment]
Interesting, thanks.

I was testing on Ubuntu 19.04 using `python-matplotlib` not `python3-matplotlib`.  It is version 2.2.3, from the Ubuntu 19.04 archives, and there was no error about _set_constrained_layout_.  What makes you think it was only added to 3.1 and above?

----

Sugar Labs used to have a concept of [platform components](https://wiki.sugarlabs.org/go/0.96/Platform_Components) which were dependencies that could be assumed to be present.  matplotlib was not among them, and isn't in OLPC OS 13.x.y (Fedora 18).

You may have noticed how Chart and one or more other activities embed a sugarpycha module.  That's why.

So adding the dependency on matplotlib in this pull request will already require us to maintain a separate _fedora18_ branch for the older releases, and not make this next release on activities.sugarlabs.org.  Stepping to a later matplotlib not yet packaged by Ubuntu or Debian is fine, just that this will require more work by packagers or integrators before our next release can be made.

It will shrink the user base for the new version until the downstreams catch up.

Alternatively, if there was a way to make the graph using the libraries already used by Sugar, we'd be able to release a new version of the activity with this feature to our existing users.

**Comment by nswarup14** [comment]
@quozl 
Thanks.

Yes, I too was using `python-matplotlib` until yesterday. However, installing `python3-matplotlib` did not help either. Then I looked up the version of matplotlib that was being installed via apt and it was 2.1.1.
After that, I installed the latest release of matplotlib which was 3.1.1 from pip.

The activity ran only after doing so, hence I believed that the `set_constrainted_layout` was only introduced in 3.1 and above. Even the official page of matplotlib says that `constrained_layout` is an experimental feature.

> Alternatively, if there was a way to make the graph using the libraries already used by Sugar, we'd be able to release a new version of the activity with this feature to our existing users.

I looked this up a lot when I first realised that Sugar does not come with matplotlib pre-installed. But there aren't a lot of options for plotting complex graphs, other than matplotlib. GTK on its own, has very limited plotting capacity.

After installing 3.1.1 via pip the activity ran, but the line graph is not re-plotting on changing the dates. I'm still in the process of investigating this.

Thanks

**Comment by quozl** [comment]
Thanks.  Yes, on Ubuntu 18.04 with Ubuntu package python-matplotlib, the _set_constrained_layout_ function is not available.

In my _hack-13_ branch, I've protected that with a `hasattr`, see [activity.py](https://github.com/sugarlabs/biorhythm/blob/hack-13/activity.py).  Looks like this;

Screenshot_ubb_2019-07-24_17:36:18

**Comment by rhl-bthr** [comment]
@nswarup14 ping

**Comment by nswarup14** [comment]
@pro-panda @quozl 
I have pushed more commits to the branch `fix-graph` of my [fork](https://github.com/nswarup14/biorhythm), but they are not being reflected in the PR.

The `diff` between my fork and _upstream master_ is shown correctly, [here](https://github.com/sugarlabs/biorhythm/compare/master...nswarup14:fix-graph?expand=1), but the PR is not being updated.

**Comment by nswarup14** [comment]
@quozl @pro-panda 
Tested #13 on Sugar v0.114 and Ubuntu 18.04 and matplotlib 2.1.1
The activity runs correctly, the dates and the line graph values are updating correctly. I do not get any truncation of the axis labels.

Kindly review, Thanks

**Comment by nswarup14** [comment]
@quozl @pro-panda 
Tested #13 on Sugar v0.114 and Ubuntu 18.04 and matplotlib 2.1.1
The activity runs correctly, the dates and the line graph values are updating correctly. I do not get any truncation of the axis labels.

Kindly review, Thanks

**Comment by quozl** [comment]
Fixes https://github.com/sugarlabs/biorhythm/issues/9

**Comment by quozl** [comment]
Fixes #9

**Pull request merged**
