### PR TITLE
Updating metadata | Add COPYING & .gitignore

### PR DESCRIPTION
**Pull request by vipulgupta2048**
**Updated following parameters**
`license`, `repository`, `tags`

Added .gitignore file.
Added COPYING
Add license in activity.py (Review)

### CODE REVIEW

**Comment by quozl** [comment]
@AlanJAS, please consent to addition of copyright and license to activity.py file.  Your commit https://github.com/sugarlabs/biorhythm/commit/0ab5b7aa52217c29988c46a674bf4f1f6fa1ad76 in 2012 did add license of GPLv3+ metadata, but the source code does not have copyright or license.

@vipulgupta2048, thanks.  Reviewed to 781bb9e.  Please consider;

* [x] do not remove `*.pyo` or `*.xo` from `.gitignore`,
* [x] tag of _Utilities_ seems wrong; it is not a program for manipulating files or the system as a whole,
* [x] tag of _Health_ seems inconsistent with available health evidence; in some countries it is illegal to claim a health benefit unless there is one; perhaps _Placebo_ may be more appropriate,
* [x] wait for response from @AlanJAS,
* [x] ensure `(C)` is after `Copyright`,
* [x] do not assert copyright to 2018; at the moment git commits by @AlanJAS only reach to 2017,
* [x] do not edit in the name of the program in place of _this program_, see [how to apply](https://github.com/sugarlabs/biorhythm/pull/12/commits/781bb9ebbc65f66efe52ca7fe6b722ec78ff5cd5#diff-7116ef0705885343c9e1b2171a06be0eR623) in the license.

**Comment by AlanJAS** [comment]
Yes. The code is GPLv3+

**Comment by vipulgupta2048** [comment]
Implemented all the changes except not sure what to put in tags now. Putting in science.

**Comment by quozl** [comment]
@AlanJAS, thanks, we will add copyright and license to source.

@vipulgupta2048, reviewed to 70f8bc4, but still not acceptable, so I've made changes and pushed to your branch, please review to a4bf61b.

**Comment by vipulgupta2048** [comment]
Thanks for the fix and showing me the right way. Good to go.

**Pull request merged**
